In [7]:
import pandas as pd
from datetime import datetime
from pytz import utc
import matplotlib.pyplot as plt

data = pd.read_csv("reviews.csv", parse_dates=['Timestamp'])
data.head()

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN

## Rating average by week

In [4]:
data['Week'] = data['Timestamp'].dt.strftime('%Y-%U')
week_average = data.groupby(['Week']).mean()

plt.figure(figsize=(25,3))
plt.show()

## Rating Average by Month

In [5]:
data['Month'] = data['Timestamp'].dt.strftime('%Y-%m')
month_average = data.groupby(['Month']).mean()
month_average

           Rating
Month
2018-01  4.429645
2018-02  4.436248
2018-03  4.421671
2018-04  4.468211
2018-05  4.396420
2018-06  4.375379
2018-07  4.393184
2018-08  4.344753
2018-09  4.347247
2018-10  4.374429
2018-11  4.386817
2018-12  4.342105
2019-01  4.401920
2019-02  4.346964
2019-03  4.333145
2019-04  4.420049
2019-05  4.405569
2019-06  4.398559
2019-07  4.382353
2019-08  4.417059
2019-09  4.451135
2019-10  4.483871
2019-11  4.493260
2019-12  4.471046
2020-01  4.439615
2020-02  4.428642
2020-03  4.480690
2020-04  4.475220
2020-05  4.448082
2020-06  4.482812
2020-07  4.517508
2020-08  4.470987
2020-09  4.485862
2020-10  4.515201
2020-11  4.479306
2020-12  4.528358
2021-01  4.551325
2021-02  4.567901
2021-03  4.589207
2021-04  4.544118

## Rating Average by Month by Course

In [6]:
data['Month'] = data['Timestamp'].dt.strftime('%Y-%m')
month_average_course = data.groupby(['Month','Course Name']).mean().unstack()
month_average_course

                                                              Rating  \
Course Name 100 Python Exercises I: Evaluate and Improve Your Skills
Month
2018-01                                               4.353448
2018-02                                               4.250000
2018-03                                               4.500000
2018-04                                               4.431034
2018-05                                               4.358696
2018-06                                               4.268293
2018-07                                               4.589286
2018-08                                               4.353659
2018-09                                               4.238636
2018-10                                               4.106061
2018-11                                               4.212766
2018-12                                               4.405172
2019-01                                               4.048780
2019-02                                               4.333333
2019-03                                               4.269231
2019-04                                               4.365854
2019-05                                               4.486111
2019-06                                               4.442308
2019-07                                               4.414634
2019-08                                               4.222222
2019-09                                               4.531250
2019-10                                               4.287500
2019-11                                               4.512195
2019-12                                               4.152778
2020-01                                               4.277778
2020-02                                               4.200000
2020-03                                               4.240000
2020-04                                               4.329268
2020-05                                               4.340909
2020-06                                               4.397059
2020-07                                               4.250000
2020-08                                               4.121622
2020-09                                               4.307692
2020-10                                               4.366667
2020-11                                               4.461538
2020-12                                               4.294118
2021-01                                               4.283333
2021-02                                               4.450000
2021-03                                               4.190476
2021-04                                               4.500000

                                                                       \
Course Name 100 Python Exercises II: Evaluate and Improve Your Skills
Month
2018-01                                                    NaN
2018-02                                                    NaN
2018-03                                                    NaN
2018-04                                                    NaN
2018-05                                                    NaN
2018-06                                                    NaN
2018-07                                                    NaN
2018-08                                                    NaN
2018-09                                                    NaN
2018-10                                                    NaN
2018-11                                                    NaN
2018-12                                                    NaN
2019-01                                                    NaN
2019-02                                                    NaN
2019-03                                                    NaN
2019-04                                                    NaN
2019-05                                                    NaN
2019-06                                               4.722222
2019-07                                               4.427273
2019-08                                               4.416667
2019-09                                               4.631579
2019-10                                               4.000000
2019-11                                               4.571429
2019-12                                               4.625000
2020-01                                               4.409091
2020-02                                               4.000000
2020-03                                               4.562500
2020-04                                               4.538462
2020-05                                               4.568182
2020-06                                               4.500000
2020-07                                               4.214286
2020-08                                               4.625000
2020-09                                               4.576923
2020-10                                               4.500000
2020-11                                               4.687500
2020-12                                               4.937500
2021-01                                               4.700000
2021-02                                               4.562500
2021-03                                               4.750000
2021-04                                                    NaN

                                         \
Course Name Data Processing with Python
Month
2018-01                        4.500000
2018-02                        4.205882
2018-03                        4.281250
2018-04                        4.468750
2018-05                        4.176471
2018-06                        4.631579
2018-07                        4.159091
2018-08                        4.411765
2018-09                        4.173913
2018-10                        4.464286
2018-11                        4.462963
2018-12                        3.985294
2019-01                        4.033333
2019-02                        4.300000
2019-03                        4.055556
2019-04                        3.812500
2019-05                        4.125000
2019-06                        4.088235
2019-07                        4.225000
2019-08                        4.600000
2019-09                        4.291667
2019-10                        4.260000
2019-11                        4.361111
2019-12                        4.104167
2020-01                        4.068966
2020-02                        4.296875
2020-03                        4.397059
2020-04                        4.078431
2020-05                        4.016949
2020-06                        4.178571
2020-07                        4.386364
2020-08                        4.578947
2020-09                        4.404762
2020-10                        4.600000
2020-11                        4.315789
2020-12                        4.350000
2021-01                        4.264706
2021-02                        3.733333
2021-03                        4.038462
2021-04                             NaN

                                                                  \
Course Name Interactive Data Visualization with Python and Bokeh
Month
2018-01                                               4.285714
2018-02                                               4.157895
2018-03                                               4.266667
2018-04                                               4.428571
2018-05                                               4.107143
2018-06                                               4.204545
2018-07                                               4.065217
2018-08                                               4.233333
2018-09                                               4.500000
2018-10                                               4.218750
2018-11                                               4.113636
2018-12                                               4.238095
2019-01                                               4.214286
2019-02                                               4.285714
2019-03                                               4.230769
2019-04                                               4.166667
2019-05                                               4.236842
2019-06                                               4.666667
2019-07                                               4.500000
2019-08                                               3.789474
2019-09                                               4.500000
2019-10                                               4.000000
2019-11                                               4.588235
2019-12                                               4.250000
2020-01                                               4.090909
2020-02                                               4.600000
2020-03                                               4.450000
2020-04                                               4.450000
2020-05                                               4.285714
2020-06                                               4.092593
2020-07                                               4.500000
2020-08                                               4.433333
2020-09                                               4.600000
2020-10                                               3.909091
2020-11                                               3.886364
2020-12                                               4.514286
2021-01                                               4.303571
2021-02                                               4.238095
2021-03                                               4.500000
2021-04                                               5.000000

                                                                      \
Course Name Learn GIS in One Hour Python for Beginners with Examples
Month
2018-01                  4.236842                           4.355422
2018-02                  4.437500                           4.363095
2018-03                  4.166667                           4.357143
2018-04                  4.250000                           4.378947
2018-05                  4.666667                           4.362654
2018-06                  4.333333                           4.273876
2018-07                  4.277778                           4.330239
2018-08                  4.100000                           4.283388
2018-09                  4.166667                           4.247967
2018-10                  4.227273                           4.259259
2018-11                  3.833333                           4.310484
2018-12                  3.925000                           4.336634
2019-01                  4.147059                           4.296992
2019-02                  4.166667                           4.155172
2019-03                  3.875000                           4.188172
2019-04                  3.437500                           4.306122
2019-05                  4.454545                           4.326667
2019-06                  4.416667                           4.057292
2019-07                  4.136364                           4.087838
2019-08                  4.181818                           4.077465
2019-09                  4.000000                           4.290541
2019-10                  4.062500                           4.137097
2019-11                  4.250000                           4.250000
2019-12                  4.382353                           4.466667
2020-01                  4.092593                           4.237288
2020-02                  3.900000                           4.294118
2020-03                  4.239130                           4.291045
2020-04                  3.828125                           4.270408
2020-05                  3.931034                           4.316667
2020-06                  3.823529                           4.130435
2020-07                  3.944444                           4.421053
2020-08                  4.222222                           4.135135
2020-09                  2.937500                           4.366667
2020-10                  3.800000                           4.325000
2020-11                  4.222222                           4.328571
2020-12                  4.200000                           4.489796
2021-01                  3.750000                           4.689189
2021-02                       NaN                           4.516667
2021-03                  4.250000                           4.333333
2021-04                       NaN                                NaN

                                                                        \
Course Name The Complete Python Course: Build 10 Professional OOP Apps
Month
2018-01                                                    NaN
2018-02                                                    NaN
2018-03                                                    NaN
2018-04                                                    NaN
2018-05                                                    NaN
2018-06                                                    NaN
2018-07                                                    NaN
2018-08                                                    NaN
2018-09                                                    NaN
2018-10                                                    NaN
2018-11                                                    NaN
2018-12                                                    NaN
2019-01                                                    NaN
2019-02                                                    NaN
2019-03                                                    NaN
2019-04                                                    NaN
2019-05                                                    NaN
2019-06                                                    NaN
2019-07                                                    NaN
2019-08                                                    NaN
2019-09                                                    NaN
2019-10                                                    NaN
2019-11                                                    NaN
2019-12                                                    NaN
2020-01                                                    NaN
2020-02                                                    NaN
2020-03                                                    NaN
2020-04                                                    NaN
2020-05                                                    NaN
2020-06                                                    NaN
2020-07                                                    NaN
2020-08                                                    NaN
2020-09                                                    NaN
2020-10                                                    NaN
2020-11                                                    NaN
2020-12                                                    NaN
2021-01                                               4.650000
2021-02                                               4.656463
2021-03                                               4.570470
2021-04                                               4.250000


Course Name The Python Mega Course: Build 10 Real World Applications
Month
2018-01                                               4.457368
2018-02                                               4.481070
2018-03                                               4.447037
2018-04                                               4.507412
2018-05                                               4.422085
2018-06                                               4.421264
2018-07                                               4.436156
2018-08                                               4.376494
2018-09                                               4.416413
2018-10                                               4.415292
2018-11                                               4.417481
2018-12                                               4.364149
2019-01                                               4.443763
2019-02                                               4.378671
2019-03                                               4.370213
2019-04                                               4.474803
2019-05                                               4.420777
2019-06                                               4.439291
2019-07                                               4.412245
2019-08                                               4.465208
2019-09                                               4.473086
2019-10                                               4.547354
2019-11                                               4.521374
2019-12                                               4.497470
2020-01                                               4.475647
2020-02                                               4.462660
2020-03                                               4.507212
2020-04                                               4.514571
2020-05                                               4.480292
2020-06                                               4.522647
2020-07                                               4.533848
2020-08                                               4.491681
2020-09                                               4.506821
2020-10                                               4.544296
2020-11                                               4.508387
2020-12                                               4.542740
2021-01                                               4.555494
2021-02                                               4.583846
2021-03                                               4.632018
2021-04                                               4.576923